import type { Car, Testimonial } from "@/lib/types";

const u = (id: string, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&auto=format&fit=crop&q=80`;

/**
 * Curated stable Unsplash photo IDs grouped by brand or affinity. We try to
 * match each car to its actual brand first; when no brand-specific photo is
 * available, we fall back to body-type/colour pools. URLs serve from
 * images.unsplash.com (whitelisted in next.config.ts).
 */
const byBrand: Record<string, string[]> = {
  BMW: [
    "1555215695-3004980ad54e",
    "1617814065893-00757125efab",
    "1607853554439-0069ec0f29b6",
    "1617469767053-d3b523a0b982",
    "1550355291-bbee04a92027",
    "1503376780353-7e6692767b70",
    "1494976388531-d1058494cdd8",
    "1617531653332-bd46c24f2068",
  ],
  Audi: [
    "1606664515524-ed2f786a0bd6",
    "1603386329225-868f9b1ee6c9",
    "1610016302534-6f67f1c968d8",
    "1606016159991-dfe4f2746ad5",
    "1606220588913-b3aacb4d2f46",
    "1542362567-b07e54358753",
    "1502877338535-766e1452684a",
    "1612825173281-9a193378527e",
  ],
  "Mercedes-Benz": [
    "1592198084033-aade902d1aae",
    "1617469767053-d3b523a0b982",
    "1580273916550-e323be2ae537",
    "1617531653332-bd46c24f2068",
    "1606664515524-ed2f786a0bd6",
    "1605559424843-9e4c228bf1c2",
  ],
  Volkswagen: [
    "1547038577-da80abbc4f19",
    "1567818735868-e71b99932e29",
    "1485291571150-772bcfc10da5",
    "1532581291347-9c39cf10a73c",
    "1605559424843-9e4c228bf1c2",
    "1606016159991-dfe4f2746ad5",
  ],
  Toyota: [
    "1605649487212-47bdab064df7",
    "1573950940509-d924ee3fd345",
    "1532581291347-9c39cf10a73c",
    "1568844293986-8d0400bd4745",
  ],
  Ford: [
    "1612544448445-b8232cff3b6c",
    "1551830820-330a71b99659",
    "1606152421802-db97b9c7a11b",
    "1492144534655-ae79c964c9d7",
  ],
  Peugeot: [
    "1606220588913-b3aacb4d2f46",
    "1617469767053-d3b523a0b982",
    "1503376780353-7e6692767b70",
    "1605559424843-9e4c228bf1c2",
  ],
  SEAT: [
    "1568844293986-8d0400bd4745",
    "1492144534655-ae79c964c9d7",
    "1605559424843-9e4c228bf1c2",
    "1532581291347-9c39cf10a73c",
  ],
  Renault: [
    "1583121274602-3e2820c69888",
    "1567899378494-47b22a2ae96a",
    "1494976388531-d1058494cdd8",
    "1606664515524-ed2f786a0bd6",
  ],
  Hyundai: [
    "1568605114967-8130f3a36994",
    "1502161254066-6c74afbf07aa",
    "1592838064575-70ed626d3a0e",
    "1532581291347-9c39cf10a73c",
  ],
  Mazda: [
    "1612825173281-9a193378527e",
    "1555215695-3004980ad54e",
    "1583121274602-3e2820c69888",
    "1567899378494-47b22a2ae96a",
  ],
  Kia: [
    "1502161254066-6c74afbf07aa",
    "1592838064575-70ed626d3a0e",
    "1568605114967-8130f3a36994",
  ],
  "Citroën": [
    "1606220588913-b3aacb4d2f46",
    "1605559424843-9e4c228bf1c2",
    "1567899378494-47b22a2ae96a",
  ],
  Nissan: [
    "1573950940509-d924ee3fd345",
    "1502161254066-6c74afbf07aa",
    "1568605114967-8130f3a36994",
  ],
  Skoda: [
    "1485291571150-772bcfc10da5",
    "1605559424843-9e4c228bf1c2",
    "1547038577-da80abbc4f19",
  ],
  Opel: [
    "1568844293986-8d0400bd4745",
    "1492144534655-ae79c964c9d7",
    "1567899378494-47b22a2ae96a",
  ],
};

// Final pad pool — authentic interior + dashboard shots used for tab variety.
const interiorPool = [
  "1486496146582-9ffcd0b2b2b7",
  "1605559424843-9e4c228bf1c2",
  "1492144534655-ae79c964c9d7",
  "1561361513-2d000a50f0dc",
  "1525609004556-c46c7d6cf023",
  "1609521263047-f8f205293f24",
];

function gallery(brand: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const push = (id: string) => {
    if (!seen.has(id) && out.length < 6) {
      seen.add(id);
      out.push(id);
    }
  };
  const brandPool = byBrand[brand] ?? [];
  for (const id of brandPool) push(id);
  for (const id of interiorPool) {
    if (out.length >= 6) break;
    push(id);
  }
  return out.map((id) => u(id));
}

type CarSeed = Omit<Car, "id" | "createdAt">;

export const seedCars: CarSeed[] = [
  {
    slug: "seat-ibiza-1-0-tsi-style-2019",
    brand: "SEAT",
    model: "Ibiza",
    version: "1.0 TSI Style",
    year: 2019,
    price: 8900,
    km: 78500,
    fuel: "gasolina",
    transmission: "manual",
    hp: 95,
    displacement: 999,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Blanco Nevada",
    previousOwners: 1,
    shortDescription:
      "Urbano ágil y eficiente, ideal para el día a día en Sevilla.",
    longDescription:
      "Este SEAT Ibiza 1.0 TSI Style ha sido la elección de quien busca un urbano de estética cuidada sin renunciar al placer de un motor turbo moderno. Su tres cilindros de 95 CV combina respuesta inmediata a bajas vueltas con consumos contenidos: una pareja perfecta para los desplazamientos diarios por el centro de Sevilla y para una escapada rápida a la Sierra Norte.\n\nEl acabado Style sube notablemente la habitabilidad sensorial: tapicería en tela combinada, climatizador, llantas de aleación de 16\", luz diurna LED y consola con pantalla táctil compatible con Apple CarPlay y Android Auto. La caja manual de 5 marchas es precisa y la dirección, ligera en aparcamiento, gana cuerpo en autovía.\n\nIdeal como primer coche premium, vehículo de empresa o para quien quiera dejar atrás un utilitario obsoleto. Mantenimiento al día en concesionario oficial, sin accidentes registrados y con todos los recordatorios de revisión completados.",
    features: [
      'Llantas de aleación 16"',
      "Climatizador automático",
      "Pantalla táctil 8\" con Apple CarPlay y Android Auto",
      "Bluetooth y dos puertos USB",
      "Faros LED diurnos",
      "Sensores de aparcamiento traseros",
      "Control de crucero",
      "Volante multifunción en cuero",
      "Dirección asistida eléctrica",
      "Limitador de velocidad",
      "Llave plegable con mando a distancia",
      "Elevalunas eléctricos en las cuatro puertas",
      "Asientos delanteros con regulación en altura",
      "Frenada automática de emergencia urbana",
      "ESP, ABS, EBD y asistente de arranque en pendiente",
      "ISOFIX en plazas traseras",
    ],
    images: gallery("SEAT"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "renault-clio-tce-90-intens-2020",
    brand: "Renault",
    model: "Clio",
    version: "TCe 90 Intens",
    year: 2020,
    price: 10500,
    km: 65200,
    fuel: "gasolina",
    transmission: "manual",
    hp: 90,
    displacement: 999,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Rojo Pasión",
    previousOwners: 1,
    shortDescription:
      "Quinta generación con tecnología de hermano mayor y diseño rotundo.",
    longDescription:
      "El Clio V cambió las reglas del segmento B y este TCe 90 Intens es la prueba: cuadro 100% digital de 7\", pantalla central vertical de 9,3\" con navegador, faros Full LED Pure Vision y un compromiso de calidad de materiales que recuerda a un Mégane reciente.\n\nEl tres cilindros TCe de 90 CV asociado a la caja manual de 5 marchas es un motor agradecido: empuja desde abajo, gira fino y consume menos de cinco litros en uso mixto. La amortiguación, ligeramente firme, transmite seguridad y aplomo en autovía sin dejar de ser confortable en ciudad.\n\nLlevado por una conductora cuidadosa y mantenido íntegramente en red oficial Renault, conserva el aspecto y los olores de un coche apenas estrenado. Perfecto para perfiles jóvenes que buscan estilo, conectividad y seguridad activa moderna.",
    features: [
      "Faros Full LED Pure Vision",
      'Llantas aleación 16" diamantadas',
      "Cuadro digital configurable 7\"",
      "Pantalla central 9,3\" con navegador integrado",
      "Apple CarPlay y Android Auto inalámbrico",
      "Climatizador automático",
      "Cámara trasera y sensores delanteros y traseros",
      "Control de crucero con limitador",
      "Frenada automática de emergencia",
      "Detección de ángulo muerto",
      "Reconocimiento de señales de tráfico",
      "Asistente de mantenimiento de carril",
      "Asientos delanteros calefactables",
      "Volante en cuero multifunción",
      "Llave manos libres con arranque por botón",
      "Modo Eco y modo Sport",
    ],
    images: gallery("Renault"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "peugeot-308-1-5-bluehdi-active-2019",
    brand: "Peugeot",
    model: "308",
    version: "1.5 BlueHDi Active",
    year: 2019,
    price: 12900,
    km: 92300,
    fuel: "diesel",
    transmission: "manual",
    hp: 130,
    displacement: 1499,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Gris Platinum",
    previousOwners: 2,
    shortDescription:
      "Compacto francés con consumo récord en autovía y i-Cockpit ergonómico.",
    longDescription:
      "Este Peugeot 308 BlueHDi 130 representa la elección lógica para quien recorre muchos kilómetros en carretera. Su motor 1.5 diésel desarrollado conjuntamente con BMW combina suavidad de marcha con un consumo medio real por debajo de los 5 l/100 km, y la caja manual de seis relaciones transmite todo el par disponible con tactos precisos.\n\nEl interior i-Cockpit, con volante compacto y cuadro elevado, redefine la postura de conducción del segmento. El acabado Active añade pantalla táctil de 9,7\", climatizador, sensores traseros y un equipamiento de seguridad muy completo. Los asientos del 308 son una referencia: aprobados por la AGR y firmes incluso en jornadas largas.\n\nDos propietarios anteriores, ambos profesionales con uso comercial cuidadoso. Distribución completada a los 90.000 km con factura, ITV recién pasada y libro de mantenimiento al día. Coche serio para quien busca rentabilidad por kilómetro.",
    features: [
      "Cuadro de instrumentación elevado i-Cockpit",
      "Pantalla táctil 9,7\" con MirrorLink",
      "Climatizador automático",
      "Sensores de aparcamiento traseros",
      "Control de crucero con limitador",
      'Llantas aleación 16"',
      "Faros antiniebla con función de giro",
      "Apple CarPlay y Android Auto",
      "Volante compacto en cuero",
      "Frenada automática de emergencia",
      "Reconocimiento de señales",
      "Asistente activo de carril",
      "Detección de fatiga del conductor",
      "Bluetooth manos libres y dos USB",
      "Acceso y arranque sin llave",
      "Encendido automático de luces y limpiaparabrisas",
    ],
    images: gallery("Peugeot"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "volkswagen-golf-1-6-tdi-advance-2018",
    brand: "Volkswagen",
    model: "Golf",
    version: "1.6 TDI Advance",
    year: 2018,
    price: 14500,
    km: 110450,
    fuel: "diesel",
    transmission: "manual",
    hp: 115,
    displacement: 1598,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Azul Atlantic",
    previousOwners: 1,
    shortDescription:
      "El compacto de referencia: dinámico, sólido y atemporal.",
    longDescription:
      "Pocos coches resisten el paso del tiempo como un Golf VII en su última actualización. Este 1.6 TDI Advance combina el motor diésel más equilibrado de la gama con un acabado que añade lo realmente importante: navegación con pantalla táctil de 8\", control de crucero adaptativo, asistente de aparcamiento Park Assist y faros antiniebla con función de giro.\n\nEn carretera, el Golf despliega ese tacto que justifica su reputación: dirección con peso medido, suspensión firme pero confortable y una insonorización que disimula los kilómetros. El consumo medio se mantiene por debajo de 5 l/100 km incluso a buen ritmo, y la caja manual de seis marchas es de las más agradables del segmento.\n\nUn solo propietario, mantenimiento íntegramente en concesionario oficial Volkswagen y embrague reciente. Llega con las cuatro ruedas en buen estado y sin intervenciones de chapa registradas. La elección segura para quien quiera invertir en un compacto que retiene valor.",
    features: [
      "Navegador integrado con pantalla 8\"",
      "Control de crucero adaptativo (ACC)",
      'Llantas aleación 16" Toronto',
      "Faros antiniebla con función Cornering",
      "Climatizador bizona Climatronic",
      "Park Assist (asistente de aparcamiento)",
      "Sensores de aparcamiento delanteros y traseros",
      "App-Connect (CarPlay y Android Auto)",
      "Volante multifunción en cuero",
      "Frenada automática Front Assist",
      "Asistente de mantenimiento de carril",
      "Reconocimiento de fatiga",
      "Acceso Keyless con arranque sin llave",
      "Bluetooth y dos puertos USB",
      "Asientos delanteros calefactables",
      "Espejos retrovisores eléctricos plegables",
      "Tapicería ArtVelours",
    ],
    images: gallery("Volkswagen"),
    isFeatured: true,
    isSold: false,
  },
  {
    slug: "ford-kuga-1-5-ecoboost-st-line-2020",
    brand: "Ford",
    model: "Kuga",
    version: "1.5 EcoBoost ST-Line",
    year: 2020,
    price: 17900,
    km: 71800,
    fuel: "gasolina",
    transmission: "manual",
    hp: 150,
    displacement: 1499,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Negro Magnetic",
    previousOwners: 1,
    shortDescription:
      "SUV familiar con look deportivo ST-Line y motor turbo de 150 CV.",
    longDescription:
      "El Ford Kuga III ST-Line es el SUV familiar que no esconde su lado dinámico. Llantas de 18\", paragolpes específicos, suspensión rebajada y volante achatado en cuero perforado: todo el repertorio de la línea ST aplicado a una carrocería con espacio sobrado para cinco adultos y un maletero útil de 645 litros.\n\nBajo el capó, el conocido EcoBoost 1.5 de tres cilindros y 150 CV ofrece prestaciones convincentes (0 a 100 en 9,7 s) con consumos razonables gracias a la desactivación selectiva de cilindros. La caja manual de seis relaciones es precisa y la nueva plataforma C2 transmite una solidez que se aleja del SUV de carretera puro: el Kuga gira con sorprendente nobleza.\n\nUn solo propietario que lo ha utilizado sin remolque, sin accidentes y con mantenimiento Ford Service. Perfecto para familia activa o profesional que quiera presencia, espacio y un toque deportivo sin pasar al mundo del PHEV.",
    features: [
      'Llantas aleación 18" ST-Line',
      "Paquete carrocería ST-Line con paragolpes específicos",
      "Suspensión deportiva rebajada",
      "Volante deportivo en cuero perforado",
      "Sistema SYNC 3 con pantalla 8\"",
      "Apple CarPlay y Android Auto",
      "Climatizador bizona",
      "Cámara trasera y sensores delanteros y traseros",
      "Faros LED con luz de carretera automática",
      "Control de crucero adaptativo con Stop & Go",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Pre-Collision Assist con frenada de emergencia",
      "Detección de fatiga",
      "Llave manos libres y arranque por botón",
      "Portón eléctrico con apertura por gesto",
      "Tapicería en tela y cuero ST-Line",
      "Cuadro digital 12,3\"",
    ],
    images: gallery("Ford"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "toyota-corolla-125h-active-tech-2021",
    brand: "Toyota",
    model: "Corolla",
    version: "125H Active Tech",
    year: 2021,
    price: 19900,
    km: 58600,
    fuel: "hibrido",
    transmission: "automatico",
    hp: 122,
    displacement: 1798,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Gris Plata",
    previousOwners: 1,
    shortDescription:
      "Híbrido auto-recargable con consumos urbanos imbatibles y etiqueta ECO.",
    longDescription:
      "La duodécima generación del Corolla devolvió a Toyota a la primera línea estética del segmento C, y este 125H Active Tech es la versión que casi nadie debería pasar por alto: híbrido auto-recargable, etiqueta ECO de la DGT y un consumo en ciudad por debajo de los 4,5 l/100 km sin enchufar nada.\n\nEl conjunto e-CVT funciona con una suavidad casi eléctrica, y los modos EV, Eco y Sport permiten ajustar la respuesta al humor del día. El acabado Active Tech añade lo importante: pantalla 8\", cámara trasera, Toyota Safety Sense de segunda generación con frenada automática, control de crucero adaptativo y asistente de carril, llantas de 16\" y el característico cuadro analógico-digital combinado.\n\nUn único propietario particular, kilometraje muy contenido para el año, y todas las revisiones realizadas en red oficial Toyota — lo que prolonga la garantía híbrida hasta 10 años o 185.000 km. Coche para quien quiera olvidarse del taller y ahorrar de verdad en gasolina.",
    features: [
      "Sistema híbrido auto-recargable Toyota 1.8 e-CVT",
      "Etiqueta ECO DGT",
      "Pantalla táctil 8\" con MirrorLink",
      "Apple CarPlay y Android Auto",
      "Cámara trasera",
      'Llantas aleación 16"',
      "Climatizador bizona",
      "Toyota Safety Sense de segunda generación",
      "Frenada automática de emergencia con detección de peatones y ciclistas",
      "Control de crucero adaptativo",
      "Asistente activo de carril con Lane Trace Assist",
      "Reconocimiento de señales de tráfico",
      "Faros LED",
      "Llave inteligente con arranque por botón",
      "Sensores de aparcamiento delanteros y traseros",
      "Cuadro mixto analógico-digital",
      "Modos de conducción EV / Eco / Normal / Sport",
      "Garantía híbrida hasta 10 años / 185.000 km con revisiones oficiales",
    ],
    images: gallery("Toyota"),
    isFeatured: true,
    isSold: false,
  },
  {
    slug: "hyundai-tucson-1-6-crdi-tecno-2021",
    brand: "Hyundai",
    model: "Tucson",
    version: "1.6 CRDi Tecno",
    year: 2021,
    price: 22500,
    km: 64200,
    fuel: "diesel",
    transmission: "manual",
    hp: 136,
    displacement: 1598,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Blanco Polar",
    previousOwners: 1,
    shortDescription:
      "El SUV con el diseño más rompedor del segmento: faros parametric hidden.",
    longDescription:
      "El Tucson NX4 fue la sorpresa estética de su año y este 1.6 CRDi Tecno traduce ese impacto visual a una propuesta racional: 136 CV de diésel maduro, transmisión manual de seis marchas y consumos por debajo de los 6 l/100 km en autopista, todo con etiqueta C de la DGT.\n\nEl interior de este Hyundai marca distancia con cualquier rival generalista: doble pantalla curva de 10,25\", consola flotante con controles capacitivos, cargador inalámbrico de móvil y un acabado ambientable con luz LED. El acabado Tecno añade además llantas de 19\", asientos calefactables, navegador con servicios conectados Bluelink y todo el paquete de seguridad activa SmartSense.\n\nUn solo propietario, kilometraje moderado y mantenimiento íntegramente en red oficial Hyundai. Resto de garantía oficial de la marca hasta los 5 años o 100.000 km. SUV ideal para familia que valore diseño, equipamiento y unas cuotas suaves de combustible.",
    features: [
      "Doble pantalla 10,25\" (cuadro digital + multimedia)",
      "Faros LED Parametric Hidden Lights",
      'Llantas aleación 19"',
      "Climatizador automático bizona",
      "Cámara 360°",
      "Hyundai SmartSense con frenada de emergencia",
      "Control de crucero adaptativo",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Asientos delanteros calefactables",
      "Tapicería en tela combinada con piel ecológica",
      "Cargador inalámbrico de móvil",
      "Llave inteligente con arranque por botón",
      "Apple CarPlay y Android Auto",
      "Servicios conectados Bluelink",
      "Iluminación interior LED ambiental",
      "Sensores de aparcamiento delanteros y traseros",
      "Resto de garantía oficial Hyundai 5 años / 100.000 km",
    ],
    images: gallery("Hyundai"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "mazda-cx5-2-0-skyactiv-g-zenith-2020",
    brand: "Mazda",
    model: "CX-5",
    version: "2.0 Skyactiv-G Zenith",
    year: 2020,
    price: 24900,
    km: 49800,
    fuel: "gasolina",
    transmission: "automatico",
    hp: 165,
    displacement: 1998,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Rojo Soul",
    previousOwners: 1,
    shortDescription:
      "El SUV más afilado del segmento, con presencia premium y mecánica atmosférica.",
    longDescription:
      "Mazda construyó este CX-5 con la lógica del Kodo design llevada al extremo: superficies tensas, faros afilados y una proporción que recuerda más a un coupé alto que a un SUV familiar. Este Zenith con el motor atmosférico Skyactiv-G de 2.0 y 165 CV es la elección refinada para quien quiera evitar tanto la sobrealimentación como la electrificación parcial.\n\nLa caja automática de seis marchas con convertidor de par responde con tactos cortos y precisos, y la dirección — calibrada con la filosofía Jinba Ittai — convierte cada curva en un pequeño placer. El interior se viste con tapicería de cuero negro o marrón, navegador con pantalla 10,25\", Bose de 10 altavoces y faros LED adaptativos.\n\nUn solo propietario que lo ha mantenido íntegramente en concesionario Mazda. Servicio de los 60.000 km recién realizado, ITV pasada y resto de garantía oficial hasta los 6 años. Para quien busca un SUV con carácter, alma japonesa y valor residual contrastado.",
    features: [
      "Motor atmosférico Skyactiv-G 2.0 165 CV",
      "Cambio automático Skyactiv-Drive 6 marchas",
      'Llantas aleación 19" diamantadas',
      "Faros LED adaptativos con luz de carretera automática",
      "Pantalla central 10,25\" con MZD Connect",
      "Apple CarPlay y Android Auto",
      "Sistema Bose Premium 10 altavoces",
      "Tapicería de cuero",
      "Asientos delanteros eléctricos calefactables y ventilados",
      "Climatizador bizona",
      "Head-Up Display Active Driving Display",
      "Cámara 360° y sensores delanteros y traseros",
      "Control de crucero adaptativo (MRCC)",
      "Frenada automática Smart City Brake",
      "Detección de ángulo muerto y tráfico cruzado",
      "Asistente activo de carril",
      "Llave inteligente con arranque por botón",
      "Portón eléctrico",
    ],
    images: gallery("Mazda"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "bmw-serie1-118i-sport-2021",
    brand: "BMW",
    model: "Serie 1",
    version: "118i Sport",
    year: 2021,
    price: 26900,
    km: 42100,
    fuel: "gasolina",
    transmission: "automatico",
    hp: 140,
    displacement: 1499,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Gris Mineral",
    previousOwners: 1,
    shortDescription:
      "F40 Sport con DCT 7v: el compacto premium con tacto auténticamente BMW.",
    longDescription:
      "La tercera generación del Serie 1 cambió a tracción delantera, pero conservó lo importante: la dirección eléctrica más comunicativa del segmento, asientos deportivos casi perfectos y una insonorización superior a la norma. Este 118i Sport monta el tres cilindros 1.5 turbo de 140 CV asociado a la caja Steptronic de doble embrague de 7 marchas: una combinación rápida, suave y notablemente sobria de consumo.\n\nEl acabado Sport añade pinzas de freno azules con relieve M, llantas de 17\", tapicería en tela combinada con cuero, alumbrado interior LED y el sistema BMW Live Cockpit Plus con doble pantalla. La calidad percibida es la marca BMW: aluminio mate en la consola, plástico blando en los puntos clave y juntas mecánicas precisas.\n\nUn propietario único, mantenimiento íntegro en BMW Service. Sin accidentes, sin cargas, batería original con buena salud. Compacto premium con la cuota correcta para quien aspira a la marca pero no quiere apretarse en un Serie 1 más antiguo.",
    features: [
      "Cambio automático Steptronic 7v de doble embrague (DCT)",
      'Llantas aleación 17" Sport',
      "Pinzas de freno azules con relieve M",
      "BMW Live Cockpit Plus con doble pantalla 8,8\"",
      "BMW Operating System 7.0",
      "Climatizador bizona automático",
      "Apple CarPlay y Android Auto",
      "Faros LED con luz alta automática",
      "Sensores de aparcamiento delanteros y traseros",
      "Cámara trasera",
      "Control de crucero con función de freno",
      "Frenada automática de emergencia con detección de peatones",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Acceso Confort y arranque sin llave",
      "Tapicería Sensatec combinada con tela Sport",
      "Volante deportivo en cuero",
      "Modos de conducción Eco Pro / Comfort / Sport",
    ],
    images: gallery("BMW"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "audi-a3-sportback-35-tfsi-s-line-2022",
    brand: "Audi",
    model: "A3 Sportback",
    version: "35 TFSI S line",
    year: 2022,
    price: 29900,
    km: 38500,
    fuel: "gasolina",
    transmission: "automatico",
    hp: 150,
    displacement: 1498,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Gris Daytona",
    previousOwners: 1,
    shortDescription:
      "El compacto premium por excelencia, en su versión S line con S tronic.",
    longDescription:
      "El A3 Sportback 8Y con paquete S line es probablemente el compacto premium que más opiniones favorables suma cuando hablamos de calidad percibida y diseño contemporáneo. Este 35 TFSI combina el 1.5 mild-hybrid de 150 CV con la caja S tronic de 7 marchas y dos embragues, una de las transmisiones más rápidas del mercado.\n\nLa silueta queda redondeada por el paquete S line: paragolpes específicos, llantas de 18\", asientos deportivos S, volante achatado y techo en negro contraste. Por dentro, virtual cockpit plus de 10,25\", MMI con pantalla central de 10,1\", climatizador trizona, faros Matrix LED y un Bang & Olufsen 3D que justifica por sí solo subir desde un acabado básico.\n\nUn solo propietario particular, libro Audi al día, ITV pasada y resto de garantía oficial. Compacto para alguien con criterio que entienda que un buen A3 envejece mejor que la mayoría de su entorno.",
    features: [
      "Motor 1.5 TFSI mild-hybrid 150 CV",
      "Cambio S tronic 7v doble embrague",
      "Paquete exterior S line con paragolpes específicos",
      'Llantas aleación 18" Audi Sport',
      "Faros Matrix LED",
      "Audi Virtual Cockpit Plus 10,25\"",
      "Pantalla central MMI 10,1\"",
      "Apple CarPlay y Android Auto inalámbrico",
      "Sistema de sonido Bang & Olufsen 3D",
      "Climatizador trizona",
      "Asientos deportivos S con tapicería en cuero/Alcantara",
      "Volante deportivo S line achatado",
      "Suspensión deportiva S line",
      "Faros antiniebla LED",
      "Sensores de aparcamiento delanteros y traseros con cámara trasera",
      "Control de crucero adaptativo (ACC)",
      "Audi pre sense con frenada de emergencia",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Acceso Confort con arranque sin llave",
    ],
    images: gallery("Audi"),
    isFeatured: true,
    isSold: false,
  },
  {
    slug: "mercedes-clase-a-200-amg-line-2021",
    brand: "Mercedes-Benz",
    model: "Clase A",
    version: "200 AMG Line",
    year: 2021,
    price: 31900,
    km: 45700,
    fuel: "gasolina",
    transmission: "automatico",
    hp: 163,
    displacement: 1332,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Negro Cosmos",
    previousOwners: 1,
    shortDescription:
      "Clase A 200 AMG Line con doble pantalla MBUX y 7G-DCT: la deportividad bien entendida.",
    longDescription:
      "El Clase A W177 AMG Line es de esos compactos que parecen mucho más coche de lo que son sobre el papel. Este 200 monta el conocido motor 1.3 turbo de Renault-Mercedes con 163 CV, asociado a la caja 7G-DCT que pasa marchas casi sin que lo notes y se acopla con suavidad incluso en marcha lenta.\n\nEl paquete AMG Line es el responsable de buena parte del impacto visual: parrilla diamante con grano cromado, paragolpes con acentos plateados, llantas AMG de 18\", suspensión rebajada y pinzas de freno con leyenda Mercedes-Benz. Por dentro, doble pantalla widescreen MBUX de 10,25\", climatizador, asientos deportivos con tapicería ARTICO/microfibra y volante AMG en cuero perforado.\n\nUn único propietario, libro de mantenimiento Mercedes al día, ITV pasada y carrocería sin intervenciones registradas. Compacto premium para quien quiera la marca de la estrella en el formato más urbano y aprovechable.",
    features: [
      "Cambio automático 7G-DCT de doble embrague",
      "Paquete exterior AMG Line",
      'Llantas aleación AMG 18"',
      "Suspensión deportiva rebajada",
      "Doble pantalla widescreen MBUX 10,25\" + 10,25\"",
      "Asistente Mercedes-Benz \"Hey Mercedes\"",
      "Climatizador bizona Thermatic",
      "Asientos deportivos AMG en ARTICO/microfibra",
      "Volante AMG en cuero perforado con palancas",
      "Iluminación ambiental LED 64 colores",
      "Faros LED High Performance",
      "Apple CarPlay y Android Auto",
      "Cámara de aparcamiento y sensores delanteros y traseros",
      "Active Brake Assist (frenada automática)",
      "Asistente activo de carril",
      "Reconocimiento de señales y limitador",
      "Llave KEYLESS-GO opcional",
      "Estribos AMG y pedales en aluminio",
    ],
    images: gallery("Mercedes-Benz"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "bmw-serie3-320d-m-sport-2022",
    brand: "BMW",
    model: "Serie 3",
    version: "320d M Sport",
    year: 2022,
    price: 36500,
    km: 52300,
    fuel: "diesel",
    transmission: "automatico",
    hp: 190,
    displacement: 1995,
    doors: 4,
    seats: 5,
    bodyType: "berlina",
    color: "Blanco Alpino",
    previousOwners: 1,
    shortDescription:
      "G20 320d M Sport: la berlina dinámica de referencia, ahora con etiqueta C.",
    longDescription:
      "El Serie 3 G20 sigue siendo, para muchos, la berlina dinámica que define el segmento, y este 320d M Sport recupera la esencia mejor entendida de la marca: motor diésel 2.0 de 190 CV con pareja de 400 Nm, caja Steptronic Sport de 8 marchas, propulsión trasera y un chasis afinado milímetro a milímetro.\n\nEl paquete M Sport completa la propuesta: paragolpes M, llantas M de 18\" o 19\", suspensión M, volante M en cuero perforado, asientos deportivos con apoyos laterales y techo en negro brillante. La doble pantalla curva BMW Live Cockpit Professional con iDrive 8 simplifica la interfaz y el sonido Harman Kardon, opcional, llena con autoridad la cabina.\n\nUn propietario, libro BMW al día, distribución por cadena (sin mantenimiento), neumáticos al 70%. Llega con la app My BMW activada y resto de garantía Premium Selection. Berlina para quien busca prestaciones, autonomía y consumos serios.",
    features: [
      "Motor 2.0 diésel BMW TwinPower Turbo 190 CV / 400 Nm",
      "Cambio automático Steptronic Sport 8 marchas",
      "Propulsión trasera",
      "Paquete M Sport con paragolpes específicos",
      'Llantas M aleación 18"',
      "Volante M en cuero perforado con levas",
      "Asientos deportivos con tapicería en cuero Vernasca",
      "Suspensión M",
      "Faros LED adaptativos",
      "BMW Live Cockpit Professional con doble pantalla 12,3\" + 14,9\"",
      "iDrive 8 con BMW Operating System 8",
      "Apple CarPlay y Android Auto inalámbrico",
      "Climatizador trizona",
      "Sensores de aparcamiento 360°",
      "Asistente de aparcamiento Parking Assistant Plus",
      "Driving Assistant con control de crucero adaptativo",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Acceso Confort y portón eléctrico",
      "Etiqueta C DGT",
    ],
    images: gallery("BMW"),
    isFeatured: true,
    isSold: false,
  },
  {
    slug: "audi-q5-40-tdi-quattro-black-line-2021",
    brand: "Audi",
    model: "Q5",
    version: "40 TDI quattro Black line",
    year: 2021,
    price: 39900,
    km: 58900,
    fuel: "diesel",
    transmission: "automatico",
    hp: 204,
    displacement: 1968,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Negro Mythos",
    previousOwners: 1,
    shortDescription:
      "FY restyling con paquete Black y quattro: SUV familiar con la etiqueta de premium serio.",
    longDescription:
      "El Audi Q5 segunda generación restyling es un SUV que mantiene su prestigio porque hace muy bien casi todo. Este 40 TDI quattro Black line monta el dos litros diésel mild-hybrid de 204 CV asociado a la caja S tronic de siete marchas y la tracción permanente quattro ultra: prestaciones, confort y aplomo en cualquier condición.\n\nEl paquete Black line aporta una estética inconfundible: parrilla single frame en negro brillante, embellecedores oscurecidos, llantas Audi Sport de 20\" y techo de cristal panorámico. Por dentro, virtual cockpit plus de 12,3\", MMI Touch con pantalla 10,1\", climatizador trizona, asientos en cuero/Alcantara y faros Matrix LED con intermitencia dinámica.\n\nUn solo propietario, kilometraje contenido para el año, mantenimiento íntegramente en red oficial Audi y resto de garantía Audi Plus. SUV ideal para profesional o familia que busque distancia, garantía y carácter Audi sin entrar en el escalón del Q7.",
    features: [
      "Tracción total quattro ultra con embrague multidisco",
      "Motor 2.0 TDI mild-hybrid 204 CV / 400 Nm",
      "Cambio S tronic 7v doble embrague",
      "Paquete exterior Black line",
      'Llantas Audi Sport 20"',
      "Techo panorámico de cristal",
      "Faros Matrix LED con intermitentes dinámicos",
      "Audi Virtual Cockpit Plus 12,3\"",
      "MMI Touch con pantalla 10,1\"",
      "Apple CarPlay y Android Auto inalámbrico",
      "Climatizador trizona",
      "Asientos delanteros eléctricos calefactables",
      "Tapicería en cuero / Alcantara con costuras de contraste",
      "Sistema de sonido B&O premium",
      "Cámara 360° y sensores delanteros y traseros",
      "Audi pre sense con frenada de emergencia",
      "Control de crucero adaptativo (ACC)",
      "Asistente activo de carril",
      "Acceso Confort y portón eléctrico con sensor de pie",
      "Suspensión adaptativa Audi drive select",
    ],
    images: gallery("Audi"),
    isFeatured: true,
    isSold: false,
  },
  // ───── 9 nuevos coches ─────
  {
    slug: "kia-sportage-1-6-crdi-drive-2020",
    brand: "Kia",
    model: "Sportage",
    version: "1.6 CRDi Drive",
    year: 2020,
    price: 18500,
    km: 73400,
    fuel: "diesel",
    transmission: "manual",
    hp: 115,
    displacement: 1598,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Gris Steel",
    previousOwners: 1,
    shortDescription:
      "Cuarta generación con la fiabilidad coreana y siete años de garantía oficial restantes.",
    longDescription:
      "El Kia Sportage QL es uno de los SUV familiares más equilibrados del mercado, y esta unidad 1.6 CRDi Drive lo demuestra con un argumento difícil de discutir: parte del periodo de garantía oficial Kia de siete años todavía vigente. Motor diésel sobrio de 115 CV, consumos por debajo de 5,5 l/100 km en mixto y caja manual de seis relaciones de tactos cortos.\n\nEl acabado Drive incluye climatizador, sensores delanteros y traseros, llantas de 17\", pantalla con Apple CarPlay y Android Auto, control de crucero y asistencias activas básicas (frenada autónoma de emergencia, mantenimiento de carril, alerta de cambio involuntario). Maletero de 491 litros y plazas traseras espaciosas para tres adultos.\n\nUn único propietario, libro Kia al día, sin accidentes y batería con un año reciente. SUV ideal para familias que prioricen tranquilidad, garantía amplia y cuotas de combustible bajas.",
    features: [
      "Motor 1.6 CRDi 115 CV",
      "Caja manual 6 velocidades",
      "Climatizador automático",
      'Llantas aleación 17"',
      "Pantalla táctil 8\" con Apple CarPlay y Android Auto",
      "Cámara trasera",
      "Sensores delanteros y traseros",
      "Control de crucero con limitador",
      "Frenada autónoma de emergencia (FCA)",
      "Asistente de mantenimiento de carril (LKA)",
      "Alerta de cambio involuntario de carril (LDW)",
      "Detección de fatiga del conductor",
      "Faros LED diurnos",
      "Volante multifunción en cuero",
      "Bluetooth y dos puertos USB",
      "ISOFIX en plazas traseras",
      "Resto de garantía oficial Kia 7 años",
    ],
    images: gallery("Kia"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "citroen-c3-puretech-110-shine-2021",
    brand: "Citroën",
    model: "C3",
    version: "PureTech 110 Shine",
    year: 2021,
    price: 11900,
    km: 41200,
    fuel: "gasolina",
    transmission: "manual",
    hp: 110,
    displacement: 1199,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Blanco Banquise",
    previousOwners: 1,
    shortDescription:
      "Urbano francés con personalidad propia y los famosos asientos Advanced Comfort.",
    longDescription:
      "El Citroën C3 III restyling apuesta por la diferenciación visual y el confort puro como banderas. Esta unidad PureTech 110 Shine es la combinación más sensata de la gama: tres cilindros turbo de 110 CV, caja manual de seis relaciones, etiqueta C DGT y consumo medio en torno a los 5,5 l/100 km.\n\nLos asientos Advanced Comfort, con espuma de alta densidad y costura específica, son uno de los argumentos comerciales del modelo y se notan especialmente en jornadas largas. La suspensión con topes hidráulicos progresivos completa la imagen de \"alfombra mágica\" típica de la marca.\n\nEl acabado Shine incluye pantalla 7\" táctil, climatizador, sensores traseros, faros 3D LED y cámara trasera. Un coche urbano alegre y sin pretensiones, kilometraje muy contenido y un solo propietario particular. Para perfiles que prioricen el confort cotidiano sobre el dinamismo deportivo.",
    features: [
      "Motor PureTech 110 CV con caja manual 6v",
      "Asientos Advanced Comfort",
      "Suspensión con topes hidráulicos progresivos",
      "Pantalla táctil 7\" con MirrorLink",
      "Apple CarPlay y Android Auto",
      "Climatizador automático",
      "Cámara trasera",
      "Sensores de aparcamiento traseros",
      'Llantas aleación 16"',
      "Faros 3D LED",
      "Volante en cuero multifunción",
      "Control de crucero con limitador",
      "Detección de fatiga",
      "Reconocimiento de señales",
      "Asistente de cambio de carril",
      "Llave plegable con cierre centralizado",
      "Etiqueta C DGT",
    ],
    images: gallery("Citroën"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "nissan-qashqai-1-5-dci-acenta-2019",
    brand: "Nissan",
    model: "Qashqai",
    version: "1.5 dCi Acenta",
    year: 2019,
    price: 15900,
    km: 88300,
    fuel: "diesel",
    transmission: "manual",
    hp: 115,
    displacement: 1461,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Gris Magnético",
    previousOwners: 1,
    shortDescription:
      "El SUV que creó el segmento, en su última versión J11 con motorización 1.5 dCi madura.",
    longDescription:
      "Pocos coches han tenido tanto impacto en el mercado europeo como el Nissan Qashqai. Esta unidad J11 restyling final monta el conocido motor 1.5 dCi de 115 CV con consumos medidos por debajo de los 5 l/100 km en autovía, caja manual de seis marchas y un comportamiento sólido sobre asfalto.\n\nEl acabado Acenta es el escalón intermedio que mejor equilibra prestaciones y precio: incluye climatizador bizona, llantas de 17\", pantalla NissanConnect 7\" con Apple CarPlay y Android Auto, sensores de aparcamiento traseros, faros LED y todo el paquete básico de seguridad activa.\n\nUn único propietario que lo ha usado mayoritariamente para autovía, mantenimiento Nissan al día, ITV pasada y sin accidentes registrados. SUV familiar para quien busque amortizar kilómetros con bajo coste y la tranquilidad de una mecánica probada hasta el aburrimiento.",
    features: [
      "Motor 1.5 dCi 115 CV diésel",
      "Caja manual 6v",
      "Climatizador bizona",
      'Llantas aleación 17"',
      "Pantalla 7\" NissanConnect",
      "Apple CarPlay y Android Auto",
      "Sensores de aparcamiento traseros",
      "Cámara trasera",
      "Faros LED diurnos",
      "Control de crucero con limitador",
      "Frenada de emergencia inteligente",
      "Detección de fatiga",
      "Reconocimiento de señales",
      "Asistente de cambio involuntario de carril",
      "Volante multifunción en cuero",
      "Bluetooth y dos puertos USB",
      "ISOFIX en plazas traseras",
    ],
    images: gallery("Nissan"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "skoda-octavia-2-0-tdi-style-2021",
    brand: "Skoda",
    model: "Octavia",
    version: "2.0 TDI Style",
    year: 2021,
    price: 21900,
    km: 67800,
    fuel: "diesel",
    transmission: "automatico",
    hp: 150,
    displacement: 1968,
    doors: 5,
    seats: 5,
    bodyType: "familiar",
    color: "Gris Quartz",
    previousOwners: 1,
    shortDescription:
      "Familiar checo con maletero de 640 litros, 2.0 TDI 150 CV y caja DSG.",
    longDescription:
      "Cuarta generación del Skoda Octavia, sin duda la mejor relación tamaño-precio del segmento C familiar. Esta unidad 2.0 TDI 150 CV con caja automática DSG de siete marchas es la versión más equilibrada para un perfil profesional o familiar: prestaciones serias, consumo en torno a 5 l/100 km en autovía y un maletero de 640 litros que humilla a cualquier compacto.\n\nEl acabado Style aporta lo que un Octavia debe llevar: pantalla central de 10\", virtual cockpit de 10,25\", climatizador trizona, llantas de 17\", faros Full LED Matrix, control de crucero adaptativo, asistente de mantenimiento de carril, frenada activa y asistencia al aparcamiento en paralelo y en batería.\n\nUn solo propietario, libro Skoda Service al día, distribución por cadena (sin mantenimiento previsto), neumáticos al 80%. Para quien quiera la racionalidad del grupo VW con la pragmática típica de Skoda.",
    features: [
      "Motor 2.0 TDI 150 CV mild-hybrid",
      "Caja automática DSG 7v",
      "Maletero 640 litros",
      "Virtual Cockpit 10,25\"",
      "Pantalla central 10\" con Apple CarPlay y Android Auto inalámbrico",
      "Climatizador trizona",
      'Llantas aleación 17"',
      "Faros Full LED Matrix",
      "Control de crucero adaptativo (ACC)",
      "Asistente activo de carril (Lane Assist)",
      "Frenada activa Front Assist",
      "Asistente de aparcamiento (Park Assist)",
      "Sensores delanteros y traseros con cámara",
      "Reconocimiento de señales",
      "Detección de fatiga",
      "Tapicería en tela combinada con piel ecológica",
      "Volante multifunción en cuero",
      "Acceso Confort con arranque sin llave",
    ],
    images: gallery("Skoda"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "opel-corsa-1-2-turbo-elegance-2021",
    brand: "Opel",
    model: "Corsa",
    version: "1.2 Turbo Elegance",
    year: 2021,
    price: 13500,
    km: 52100,
    fuel: "gasolina",
    transmission: "manual",
    hp: 100,
    displacement: 1199,
    doors: 5,
    seats: 5,
    bodyType: "compacto",
    color: "Rojo Voltaic",
    previousOwners: 1,
    shortDescription:
      "Sexta generación del Corsa, basada en plataforma PSA, con tres cilindros turbo y eficiencia notable.",
    longDescription:
      "El Opel Corsa F estrenó plataforma compartida con el Peugeot 208, lo que se nota tanto en consumos como en agilidad de chasis. Este 1.2 Turbo Elegance monta el tres cilindros turbo de 100 CV con caja manual de seis marchas: prestaciones suficientes para autovía, consumo en torno a los 5 l/100 km y un cuerpo compacto que se mueve con soltura por cualquier ciudad.\n\nEl acabado Elegance es la apuesta segura: faros IntelliLux LED, climatizador, pantalla 7\", control de crucero, frenada automática, asistente de mantenimiento de carril, asientos certificados AGR y volante en cuero. Una propuesta urbana premium sin pasar al peldaño Ultimate.\n\nUn solo propietario particular, mantenimiento Opel al día, ITV pasada y sin accidentes registrados. Para perfiles jóvenes o segundo coche familiar moderno, eficiente y con etiqueta C de la DGT.",
    features: [
      "Motor 1.2 Turbo 100 CV",
      "Caja manual 6v",
      "Faros IntelliLux LED",
      "Asientos certificados AGR",
      "Pantalla táctil 7\" con Apple CarPlay y Android Auto",
      "Climatizador automático",
      "Control de crucero",
      'Llantas aleación 16"',
      "Frenada automática de emergencia",
      "Asistente de mantenimiento de carril",
      "Reconocimiento de señales",
      "Sensores de aparcamiento traseros",
      "Cámara trasera",
      "Detección de fatiga",
      "Volante multifunción en cuero",
      "Bluetooth y dos puertos USB",
      "Etiqueta C DGT",
    ],
    images: gallery("Opel"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "peugeot-3008-1-5-bluehdi-gt-line-2020",
    brand: "Peugeot",
    model: "3008",
    version: "1.5 BlueHDi GT Line",
    year: 2020,
    price: 22900,
    km: 68400,
    fuel: "diesel",
    transmission: "automatico",
    hp: 130,
    displacement: 1499,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Gris Artense",
    previousOwners: 1,
    shortDescription:
      "SUV francés con paquete GT Line, EAT8 y el i-Cockpit más avanzado de la marca.",
    longDescription:
      "El Peugeot 3008 II GT Line es uno de los SUV con mejor presencia visual del segmento C, y esta unidad lo borda en su configuración más vendida: motor diésel 1.5 BlueHDi de 130 CV, caja automática EAT8 de ocho relaciones y consumos por debajo de los 5,5 l/100 km en autovía.\n\nEl paquete GT Line añade detalles que distancian la imagen del 3008 estándar: parrilla específica con detalles cromados, llantas de 18\" diamantadas, asientos deportivos en tela y ecuir mistral con costuras rojas, volante en cuero perforado, pedales aluminio y techo en color contrastado. El i-Cockpit con cuadro digital 12,3\" y pantalla central 8\" sigue siendo de los más limpios del mercado.\n\nUn solo propietario particular, libro Peugeot al día, ITV pasada y sin accidentes registrados. SUV familiar para quienes buscan distinción visual y la tecnología más reciente del grupo PSA-Stellantis.",
    features: [
      "Motor 1.5 BlueHDi 130 CV",
      "Cambio automático EAT8 8v",
      "Paquete GT Line con detalles específicos",
      'Llantas aleación 18" diamantadas',
      "i-Cockpit con cuadro digital 12,3\"",
      "Pantalla central 8\" táctil",
      "Apple CarPlay y Android Auto",
      "Climatizador bizona",
      "Asientos deportivos GT Line en tela y ecuir",
      "Volante deportivo en cuero perforado",
      "Pedales en aluminio",
      "Faros LED Full Diamond",
      "Cámara trasera y sensores delanteros y traseros",
      "Control de crucero adaptativo",
      "Asistente activo de carril",
      "Frenada automática de emergencia",
      "Reconocimiento de señales",
      "Acceso sin llave con arranque por botón",
      "Portón eléctrico",
    ],
    images: gallery("Peugeot"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "volkswagen-tiguan-2-0-tdi-life-2022",
    brand: "Volkswagen",
    model: "Tiguan",
    version: "2.0 TDI Life",
    year: 2022,
    price: 28900,
    km: 41200,
    fuel: "diesel",
    transmission: "automatico",
    hp: 150,
    displacement: 1968,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Blanco Puro",
    previousOwners: 1,
    shortDescription:
      "Segunda generación restyling con DSG7, paquete Life y kilometraje muy contenido.",
    longDescription:
      "El Volkswagen Tiguan AD1 restyling es el SUV familiar serio y bien construido por excelencia. Esta unidad 2.0 TDI Life de 150 CV con caja DSG de siete marchas combina lo mejor de la mecánica VW con un kilometraje sorprendentemente contenido para un coche de empresa.\n\nEl acabado Life incluye lo que muchos buscan: cuadro digital Active Info Display de 10,25\", pantalla central de 8\" con App-Connect, climatizador trizona, llantas de 17\", faros LED, control de crucero adaptativo (ACC), Front Assist con frenada de emergencia, Lane Assist, Side Assist y reconocimiento de señales. El maletero de 615 litros se queda en 1.655 con los asientos abatidos.\n\nUn solo propietario, mantenimiento Volkswagen Service al día, ITV pasada y sin accidentes. SUV ideal para familias que necesiten habitabilidad real, fiabilidad probada y la tranquilidad de un servicio postventa amplio.",
    features: [
      "Motor 2.0 TDI 150 CV mild-hybrid",
      "Cambio DSG 7v doble embrague",
      "Active Info Display 10,25\"",
      "Pantalla central 8\" con App-Connect",
      "Apple CarPlay y Android Auto",
      "Climatizador trizona",
      'Llantas aleación 17"',
      "Faros LED",
      "Control de crucero adaptativo (ACC)",
      "Front Assist con frenada de emergencia",
      "Lane Assist (asistente de carril)",
      "Side Assist (detección de ángulo muerto)",
      "Reconocimiento de señales",
      "Sensores delanteros y traseros con cámara",
      "Volante multifunción en cuero",
      "Tapicería ArtVelours",
      "Acceso Keyless con arranque sin llave",
      "Portón eléctrico Easy Open",
    ],
    images: gallery("Volkswagen"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "audi-a4-35-tdi-s-tronic-advanced-2021",
    brand: "Audi",
    model: "A4",
    version: "35 TDI S tronic Advanced",
    year: 2021,
    price: 32900,
    km: 54600,
    fuel: "diesel",
    transmission: "automatico",
    hp: 163,
    displacement: 1968,
    doors: 4,
    seats: 5,
    bodyType: "berlina",
    color: "Azul Navarra",
    previousOwners: 1,
    shortDescription:
      "Berlina premium con 35 TDI mild-hybrid, S tronic y todo el paquete Advanced.",
    longDescription:
      "El Audi A4 B9 restyling sigue siendo, pasados los años, una de las berlinas premium más bien construidas del mercado. Esta unidad 35 TDI Advanced 163 CV con sistema mild-hybrid de 12 V combina prestaciones suficientes (0-100 en 8,8 s) con consumos por debajo de los 5 l/100 km en autovía. La caja S tronic de siete marchas y doble embrague encadena marchas con suavidad ejemplar.\n\nEl acabado Advanced sube notablemente la imagen exterior con paragolpes específicos, llantas Audi Sport de 18\", embellecedores S line satinados y faros Matrix LED con intermitentes dinámicos. Por dentro: virtual cockpit plus de 12,3\", MMI Touch de 10,1\", climatizador trizona, asientos en tela/cuero sintético y todo el paquete Audi pre sense de seguridad activa.\n\nUn único propietario, libro Audi Service al día, ITV pasada, sin accidentes y resto de garantía Audi Plus. Berlina para profesional exigente que valore distancia, sobriedad y calidad táctil sin entrar en el escalón Premium.",
    features: [
      "Motor 2.0 TDI 163 CV mild-hybrid 12V",
      "Cambio S tronic 7v doble embrague",
      "Paquete exterior Advanced",
      'Llantas Audi Sport 18"',
      "Faros Matrix LED con intermitencia dinámica",
      "Audi Virtual Cockpit Plus 12,3\"",
      "MMI Touch 10,1\"",
      "Apple CarPlay y Android Auto inalámbrico",
      "Climatizador trizona",
      "Asientos deportivos S line en tela / piel ecológica",
      "Volante multifunción en cuero perforado",
      "Sensores delanteros y traseros con cámara",
      "Control de crucero adaptativo (ACC)",
      "Audi pre sense con frenada de emergencia",
      "Asistente activo de carril",
      "Reconocimiento de señales",
      "Acceso Confort y arranque por botón",
      "Maletero eléctrico",
      "Resto de garantía Audi Plus",
    ],
    images: gallery("Audi"),
    isFeatured: false,
    isSold: false,
  },
  {
    slug: "mercedes-glc-220d-4matic-amg-line-2022",
    brand: "Mercedes-Benz",
    model: "GLC",
    version: "220d 4MATIC AMG Line",
    year: 2022,
    price: 44900,
    km: 39800,
    fuel: "diesel",
    transmission: "automatico",
    hp: 194,
    displacement: 1993,
    doors: 5,
    seats: 5,
    bodyType: "suv",
    color: "Negro Obsidiana",
    previousOwners: 1,
    shortDescription:
      "Segunda generación X254 con tracción 4MATIC, MBUX 11,9\" y paquete AMG Line.",
    longDescription:
      "El Mercedes-Benz GLC X254 representa el SUV premium ideal para distancias largas y familia exigente. Esta unidad 220d 4MATIC AMG Line monta el motor diésel 2.0 mild-hybrid de 194 CV combinado con un módulo eléctrico ISG de 23 CV adicional para arranques y aceleraciones. Caja 9G-TRONIC y tracción permanente 4MATIC: prestaciones serias y consumo en torno a los 6 l/100 km.\n\nEl paquete AMG Line aplica el repertorio visual habitual: parrilla AMG con grano cromado, paragolpes específicos, llantas AMG de 19\", suspensión deportiva (10 mm más baja), volante AMG en cuero perforado y embellecedores en aluminio. La cabina, presidida por el sistema MBUX con pantalla central vertical de 11,9\" y cuadro digital de 12,3\", marca uno de los mejores estados del arte en infotainment.\n\nUn único propietario, libro Mercedes Service al día, kilometraje contenido y resto de garantía oficial Mercedes hasta los 4 años o 100.000 km. SUV ideal para profesional que recorra mucha autopista y valore distancia, equipamiento y la marca de la estrella.",
    features: [
      "Motor 2.0 diésel 194 CV mild-hybrid + ISG 23 CV",
      "Tracción permanente 4MATIC",
      "Cambio automático 9G-TRONIC",
      "Paquete exterior e interior AMG Line",
      'Llantas AMG 19"',
      "Suspensión deportiva AMG",
      "MBUX con pantalla vertical 11,9\"",
      "Cuadro digital 12,3\"",
      "Apple CarPlay y Android Auto inalámbrico",
      "Asistente vocal Hey Mercedes",
      "Climatizador trizona THERMATIC",
      "Faros MULTIBEAM LED",
      "Asientos deportivos AMG en cuero ARTICO",
      "Volante AMG en cuero perforado con palancas",
      "Iluminación ambiental LED 64 colores",
      "Cámara 360° Surround View",
      "Active Distance Assist DISTRONIC",
      "Active Lane Keeping Assist",
      "Acceso KEYLESS-GO Comfort",
      "Portón eléctrico HANDS-FREE ACCESS",
    ],
    images: gallery("Mercedes-Benz"),
    isFeatured: true,
    isSold: false,
  },
];

export const seedTestimonials: Omit<Testimonial, "id" | "createdAt">[] = [
  {
    name: "Lucía Hernández",
    city: "Sevilla",
    carBought: "Audi A3 Sportback 35 TFSI",
    rating: 5,
    review:
      "Compré el A3 sin desplazarme y me lo trajeron a Mairena con todo en regla. La transparencia con la documentación y el estado real fue total. Repetiré.",
    photo: u("1494790108377-be9c29b29330", 320),
  },
  {
    name: "Javier Romero",
    city: "Dos Hermanas",
    carBought: "BMW Serie 3 320d M Sport",
    rating: 5,
    review:
      "Llevaba meses buscando un 3 con buena historia. En AutoSelect me enseñaron las facturas de mantenimiento, pasamos la prueba sin prisas y me ayudaron con la financiación. Ojalá todos los compradores fueran así.",
    photo: u("1500648767791-00dcc994a43e", 320),
  },
  {
    name: "Carmen Vázquez",
    city: "Alcalá de Guadaíra",
    carBought: "Toyota Corolla 125H",
    rating: 5,
    review:
      "Buscaba algo eficiente para el día a día y un coche híbrido bien revisado. Me explicaron diferencias entre versiones y me orientaron sin presión. El Corolla está como nuevo.",
    photo: u("1438761681033-6461ffad8d80", 320),
  },
  {
    name: "Pablo Castaño",
    city: "Mairena del Aljarafe",
    carBought: "Ford Kuga ST-Line",
    rating: 5,
    review:
      "Necesitaba un SUV familiar y el Kuga me convenció en la prueba. Trato cercano, sin presión y un precio muy competitivo. Me entregaron el coche con la ITV recién pasada y los neumáticos nuevos.",
    photo: u("1507003211169-0a1dd7228f2d", 320),
  },
  {
    name: "Marta Delgado",
    city: "Sevilla",
    carBought: "Mercedes Clase A 200 AMG",
    rating: 5,
    review:
      "Quería un Clase A con AMG Line de un solo dueño y AutoSelect lo encontró en una semana. Sin sorpresas, sin letra pequeña. La garantía adicional me dio mucha tranquilidad.",
    photo: u("1544005313-94ddf0286df2", 320),
  },
  {
    name: "Diego Marín",
    city: "La Rinconada",
    carBought: "Volkswagen Golf 1.6 TDI",
    rating: 5,
    review:
      "Coche segundo de la familia, buscábamos un Golf serio y rentable. Pasamos por el taller, comprobamos todo y entregaron el coche con embrague nuevo de obsequio. Profesionales.",
    photo: u("1472099645785-5658abf4ff4e", 320),
  },
  {
    name: "Andrea Salas",
    city: "Bormujos",
    carBought: "Hyundai Tucson CRDi Tecno",
    rating: 5,
    review:
      "Cambiamos un C4 viejo por un Tucson y la diferencia es enorme. Nos dieron una tasación honesta del nuestro y financiamos la diferencia con cuotas razonables. Recomendados.",
    photo: u("1487412720507-e7ab37603c6f", 320),
  },
];
